### ISSUE TITLE
Install xdebug when build arg is present

### ISSUE THREAD

**Issue by radmen** [DeDocker/php#1]
Image should have directive

```
ONBUILD RUN test "$XDEBUG_INSTALL" = "1" && ./install_xdebug.sh
```

Since there's no package for alpine linux xdebug has to be compiled from sources.

**Comment by radmen** [comment]
Some steps which will help
1. Add testing repo:
   
   ```
   http://dl-cdn.alpinelinux.org/alpine/edge/testing
   ```
2. Install xdebug:
   
   ```
   apk add --no-cache php7-xdebug
   ```
3. Set following values to config
   
   ```
   xdebug.remote_enable=1
   xdebug.remote_autostart=0
   xdebug.remote_connect_back=1
   ```

**Comment by golonix** [comment]
I have an idea for that. Will try to make that happen 😄
